[project]
id = "flowerpot_prototype"
name = "Flowerpot Prototype"
version = "0.0.1"

[components.tile]
type = "Empty"
name = "Tile"
description = "A tag belonging to all tile entities."
attributes = ["Debuggable"]

[components.west_neighbor]
type = "EntityId"
name = "WestNeighhbor"
description = "The entity ID west of this entity."
attributes = ["Debuggable"]

[components.north_neighbor]
type = "EntityId"
name = "NorthNeighhbor"
description = "The entity ID north of this entity."
attributes = ["Debuggable"]

[components.east_neighbor]
type = "EntityId"
name = "EastNeighhbor"
description = "The entity ID east of this entity."
attributes = ["Debuggable"]

[components.south_neighbor]
type = "EntityId"
name = "SouthNeighhbor"
description = "The entity ID south of this entity."
attributes = ["Debuggable"]

[components.soil]
type = "Empty"
name = "soil"
description = "A tag belonging to all soil tiles."
attributes = ["Debuggable"]

[components.cover_crop_occupant]
type = "EntityId"
name = "FaunaOccupant"
description = "The entity ID of the cover crop class occupying this tile."
attributes = ["Debuggable"]

[components.cover_crop]
type = "Empty"
name = "SmallCrop"
description = "A tag given to all cover crop entities."
attributes = ["Debuggable"]

[components.sustenance]
type = "F32"
name = "Sustenance"
description = "The amount of fullness restored by devouring this entity."
attributes = ["Debuggable"]

[components.map_position]
type = "Vec2"
name = "MapPosition"
description = "The position of this entity in map coordinates."
attributes = ["Debuggable"]

[components.map_elevation]
type = "F32"
name = "MapElevation"
description = "The elevation of this entity above the map in meters."
attributes = ["Debuggable"]

[components.on_tile]
type = "EntityId"
name = "OnTile"
description = "The entity ID of the tile that this entity is on top of."
attributes = ["Debuggable"]

[components.fauna]
type = "Empty"
name = "Fauna"
description = "A tag belonging to all fauna entities."
attributes = ["Debuggable"]

[components.stamina]
type = "F32"
name = "Stamina"
description = "The amount of energy a fauna has available to perform actions."
attributes = ["Debuggable"]

[components.passive_metabolism]
type = "F32"
name = "PassiveMetabolism"
description = "The amount of stamina that a fauna passively regains per second."
attributes = ["Debuggable"]

[components.movement_cost]
type = "F32"
name = "MovementCost"
description = "The amount of stamina a fauna requires to move by a tile."
attributes = ["Debuggable"]

[components.movement_step]
type = "F32"
name = "MovementStep"
description = "The time in seconds through the current movement."
attributes = ["Debuggable"]

[components.movement_duration]
type = "F32"
name = "MovementDuration"
description = "The duration in seconds of the current movement."
attributes = ["Debuggable"]

[components.movement_start]
type = "Vec2"
name = "MovementStart"
description = "The start (in map coordinates) of the current movement."
attributes = ["Debuggable"]

[components.movement_target]
type = "Vec2"
name = "MovementTarget"
description = "The target (in map coordinates) of the current movement."
attributes = ["Debuggable"]

[components.movement_height]
type = "F32"
name = "MovementHeight"
description = "The peak jump height of the current movement."
attributes = ["Debuggable"]

[components.bunny]
type = "Empty"
name = "Bunny"
description = "An herbivorous bunny rabbit that eats cover crops."
attributes = ["Debuggable"]

[components.movement_distance]
type = "F32"
name = "MovementDistance"
description = "The distance (in map coordinates) of a single movement."
attributes = ["Debuggable"]

[components.fullness]
type = "F32"
name = "Fullness"
description = "The fullness (opposite of hunger) of this entity."
attributes = ["Debuggable"]

[components.hunger_rate]
type = "F32"
name = "HungerRate"
description = "The rate at which this entity's fullness is depleted per second."
attributes = ["Debuggable"]

[components.search_cover_crop_radius]
type = "F32"
name = "SearchSmallCropRadius"
description = "The search radius to search for cover crops in."
attributes = ["Debuggable"]

[components.search_cover_crop_result]
type = "EntityId"
name = "SearchSmallCropResult"
description = "The result of a search for cover crops."
attributes = ["Debuggable"]

[components.player]
name = "Player"
description = "Player-related components."

[components."player::head_ref"]
type = "EntityId"
name = "PlayerHeadRef"
description = "The player's head."
attributes = ["Debuggable"]

[components."player::movement_direction"]
type = "Vec2"
atttributes = ["Debuggable"]

[components."player::yaw"]
type = "F32"
attributes = ["Debuggable"]

[components."player::pitch"]
type = "F32"
attributes = ["Debuggable"]

[components."player::left_hand_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[components."player::right_hand_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[components."player::held_item_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[components.crafting]
name = "Crafting"
description = "All components related to crafting."

[components."crafting::recipe"]
type = "Empty"
attributes = ["Debuggable"]

[components."crafting::primary_ingredient"]
type = "EntityId"
attributes = ["Debuggable"]

[components."crafting::secondary_ingredient"]
type = "EntityId"
attributes = ["Debuggable"]

[components."crafting::primary_yield"]
type = "EntityId"
attributes = ["Debuggable"]

[components."crafting::secondary_yield"]
type = "EntityId"
attributes = ["Debuggable"]

[messages.grow_tick]
description = "Grows flora."
fields = {}

[messages.player_movement_input]
name = "PlayerMovementInput"
description = "Client-to-server message to set the movement state of a player."

[messages.player_movement_input.fields.yaw]
type = "F32"
description = "The new yaw (in radians) of the player."

[messages.player_movement_input.fields.pitch]
type = "F32"
description = "The new pitch (in radians) of the player."

[messages.player_movement_input.fields.direction]
type = "Vec2"
description = "The movement direction of the player relative to the yaw. This is normalized to unit length."

[messages.player_craft_input]
name = "PlayerCraftInput"
description = "Message sent when a player attempts to craft the two held items."
fields = {}
