[project]
id = "flowerpot_prototype"
name = "Flowerpot Prototype"
version = "0.0.1"

includes = [
  "schema/crafting.toml",
  "schema/crops.toml",
  "schema/items.toml",
  "schema/map.toml",
  "schema/player.toml",
]

[components.cover_crop_occupant]
type = "EntityId"
name = "FaunaOccupant"
description = "The entity ID of the cover crop class occupying this tile."
attributes = ["Debuggable", "Networked"]

[components.cover_crop]
type = "Empty"
name = "SmallCrop"
description = "A tag given to all cover crop entities."
attributes = ["Debuggable"]

[components.sustenance]
type = "F32"
name = "Sustenance"
description = "The amount of fullness restored by devouring this entity."
attributes = ["Debuggable"]

[components.fauna]
type = "Empty"
name = "Fauna"
description = "A tag belonging to all fauna entities."
attributes = ["Debuggable"]

[components.stamina]
type = "F32"
name = "Stamina"
description = "The amount of energy a fauna has available to perform actions."
attributes = ["Debuggable"]

[components.passive_metabolism]
type = "F32"
name = "PassiveMetabolism"
description = "The amount of stamina that a fauna passively regains per second."
attributes = ["Debuggable"]

[components.movement_cost]
type = "F32"
name = "MovementCost"
description = "The amount of stamina a fauna requires to move by a tile."
attributes = ["Debuggable"]

[components.movement_step]
type = "F32"
name = "MovementStep"
description = "The time in seconds through the current movement."
attributes = ["Debuggable"]

[components.movement_duration]
type = "F32"
name = "MovementDuration"
description = "The duration in seconds of the current movement."
attributes = ["Debuggable"]

[components.movement_start]
type = "Vec2"
name = "MovementStart"
description = "The start (in map coordinates) of the current movement."
attributes = ["Debuggable"]

[components.movement_target]
type = "Vec2"
name = "MovementTarget"
description = "The target (in map coordinates) of the current movement."
attributes = ["Debuggable"]

[components.movement_height]
type = "F32"
name = "MovementHeight"
description = "The peak jump height of the current movement."
attributes = ["Debuggable"]

[components.bunny]
type = "Empty"
name = "Bunny"
description = "An herbivorous bunny rabbit that eats cover crops."
attributes = ["Debuggable"]

[components.movement_distance]
type = "F32"
name = "MovementDistance"
description = "The distance (in map coordinates) of a single movement."
attributes = ["Debuggable"]

[components.fullness]
type = "F32"
name = "Fullness"
description = "The fullness (opposite of hunger) of this entity."
attributes = ["Debuggable"]

[components.hunger_rate]
type = "F32"
name = "HungerRate"
description = "The rate at which this entity's fullness is depleted per second."
attributes = ["Debuggable"]

[components.search_cover_crop_radius]
type = "F32"
name = "SearchSmallCropRadius"
description = "The search radius to search for cover crops in."
attributes = ["Debuggable"]

[components.search_cover_crop_result]
type = "EntityId"
name = "SearchSmallCropResult"
description = "The result of a search for cover crops."
attributes = ["Debuggable"]

[messages.grow_tick]
description = "Grows flora."
fields = {}
