[package]
name = "flowerpot_prototype"

edition = "2021"
publish = false
version = "0.0.1"

[dependencies]
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", rev = "22dd65f" }
parry2d = "0.13"
slab = "0.4"
rand_chacha = "0.3.1"
palette = "0.7.2"

[[bin]]
name = "client_flowerpot_prototype"
path = "src/client.rs"
required-features = ["client"]

[[bin]]
name = "server_flowerpot_prototype"
path = "src/server.rs"
required-features = ["server"]

[features]
client = ["ambient_api/client"]
server = ["ambient_api/server"]