[components.items]
name = "Items"
description = "Item-related components."

[components."items::class_ref"]
type = "EntityId"
name = "ClassRef"
description = "A reference to this entities' item class."
attributes = ["Debuggable", "Networked"]

[components."items::search_radius"]
type = "F32"
name = "Search Radius"
description = """
Attach this component to an entity with a map position to search the map for
the nearest item within the search radius. The result will be placed into the
search_result component.
"""

[components."items::search_result"]
type = "EntityId"
name = "Search Result"
description = "A result of a spatial query for items."
attributes = ["Debuggable"]

[components."items::prefab_path"]
type = "String"
name = "PrefabPath"
description = "The asset path to this item's model prefab."
attributes = ["Debuggable", "Networked"]

[components."items::plantable_crop_class_ref"]
type = "EntityId"
name = "PlantableCropClassRef"
description = "Add to an item to make it plant the given crop class when used. This component should be replaced with a more robust item actions system."
attributes = ["Debuggable", "Networked"]
