[components.player]
name = "Player"
description = "Player-related components."

[components."player::head_ref"]
type = "EntityId"
name = "HeadRef"
attributes = ["Debuggable"]
description = """
A reference to this player's head entity. Used client-side only in order to
update the main camera's transform.
"""

[components."player::loaded"]
type = "Empty"
name = "Loaded"
attributes = ["Debuggable", "Networked"]
description = """
A tag attached to a player entity when all of its server-side setup has been
completed and client-side setup is ready to begin.
"""

[components."player::local_player_ref"]
type = "EntityId"
name = "LocalPlayerRef"
attributes = ["Debuggable", "MaybeResource"]
description = """
A client-only resource referencing the root of the local player entity.
"""

[components."player::local_player"]
type = "Empty"
name = "LocalPlayer"
attributes = ["Debuggable"]
description = """
A client-only tag attached to local player entities. Used to differentiate
systems specific to other players from systems specific to the local player.
"""

[components."player::movement_direction"]
type = "Vec2"
atttributes = ["Debuggable"]

[components."player::yaw"]
type = "F32"
attributes = ["Debuggable", "Networked"]

[components."player::pitch"]
type = "F32"
attributes = ["Debuggable", "Networked"]

[components."player::local_yaw"]
type = "F32"
attributes = ["Debuggable"]
description = "Local-only player yaw."

[components."player::local_pitch"]
type = "F32"
attributes = ["Debuggable"]
description = "Local-only player pitch."

[components."player::left_hand_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[components."player::right_hand_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[components."player::held_item_ref"]
type = "EntityId"
attributes = ["Debuggable", "Networked"]

[messages.player_movement_input]
name = "PlayerMovementInput"
description = "Client-to-server message to set the movement state of a player."

[messages.player_movement_input.fields.yaw]
type = "F32"
description = "The new yaw (in radians) of the player."

[messages.player_movement_input.fields.pitch]
type = "F32"
description = "The new pitch (in radians) of the player."

[messages.player_movement_input.fields.direction]
type = "Vec2"
description = "The movement direction of the player relative to the yaw. This is normalized to unit length."

[messages.player_craft_input]
name = "PlayerCraftInput"
description = "Message sent when a player attempts to craft the two held items."
fields = {}